apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-ci-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-ci-cd-demo
  template:
    metadata:
      labels:
        app: gke-ci-cd-demo
    spec:
      containers:
      - name: gke-ci-cd-demo
        image: gcr.io/mmmm-452606/my-app:latest  # ✅ 프로젝트 ID & 이미지명 확인
        imagePullPolicy: Always
        ports:
        - containerPort: 80
