name: CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 1️⃣ Google Cloud 인증
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      # 2️⃣ gke-gcloud-auth-plugin 설치 (에러 해결)
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      # 3️⃣ Docker 빌드 & Artifact Registry Push
      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/my-app
        run: |
          gcloud auth configure-docker
          docker build -t $IMAGE_NAME:$GITHUB_SHA .
          docker push $IMAGE_NAME:$GITHUB_SHA

      # 4️⃣ GKE 클러스터 인증
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials gke-ci-cd-cluster --region us-central1-a

      # 5️⃣ Kubernetes Deployment 적용
      - name: Deploy to GKE
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/my-app
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_NAME:$GITHUB_SHA|g" k8s/deployment.yml
          kubectl apply -f k8s/deployment.yml
