name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        env:
          GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        run: |
          echo "$GCP_SERVICE_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project mmmm-452606

      # ✅ GKE 인증 플러그인 수동 설치
      - name: Install GKE authentication plugin
        run: |
          curl -sSL https://github.com/google-gke/gke-gcloud-auth-plugin/releases/download/v0.1.0/gke-gcloud-auth-plugin-linux-amd64 -o /usr/local/bin/gke-gcloud-auth-plugin
          chmod +x /usr/local/bin/gke-gcloud-auth-plugin

      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials gke-ci-cd-cluster --region us-central1-a

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yml  # GKE에 배포할 Deployment 파일
          kubectl apply -f k8s/service.yml     # GKE에 서비스 설정 파일

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc gke-ci-cd-demo-service
