name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        env:
          GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        run: |
          echo "$GCP_SERVICE_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project mmmm-452606
